/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** A filter tree compiled once, evaluated many times. */
export declare class Predicate {
  constructor(filters: string, options?: string | undefined | null)
  /** Test one record (JSON). */
  test(record: string): boolean
  /** Positions of the records (a JSON array) satisfying the predicate. */
  filterIndices(records: string): Array<number>
}

/** `distributeNegation`: envelope around the distributed `ConditionPlan`. */
export declare function distributeNegation(plan: string): string

/** One-shot evaluation: does the record satisfy the filters? */
export declare function matches(filters: string, record: string, options?: string | undefined | null): boolean

/** `FILTER_OPERATOR_SEMANTICS` as JSON. */
export declare function operatorSemantics(): string

/**
 * `ExpressionFiltersParser.parse()` (schemaless): IR JSON of the root
 * group. An absent input yields an empty AND group.
 */
export declare function parseExpressionFilters(input?: string | undefined | null): string

/**
 * `ExpressionFiltersParser.parseExact()` (schemaless): IR JSON of the
 * raw expression tree.
 */
export declare function parseExpressionFiltersExact(input: string): string

/**
 * `planCondition`: condition IR JSON (values may be host references) to
 * an envelope around `ConditionPlan` JSON (`null` for an empty tree).
 */
export declare function planCondition(condition: string, options?: string | undefined | null): string
